# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2b4bbf7a7e72047f05052a229a33ffe656d5496c31827149706ec5aad0cbd667256f1d8b02bbac61c50bed8e484962468e13bc74382ee902c99f1cfbabfdc68e

test:
  secret_key_base: 37fa7ba9444ca5154dc08bd1df62cfce82bdb0d74143cf562ab9dade9009a9b45c502128cd4d28b2930ddcaecdbd6f00ac04e369f38020b20763e638aa4c5b0c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
